#!/bin/sh

# Launch a rabbitmq SERVICE that will be named orbital-command. You should
# define a specific user and password for the RabbitMQ service, they can be whatever
# you want. This service will be on the overmind network.

docker service create -d --network overmind --name orbital-command -e RABBITMQ_DEFAULT_USER=root -e RABBITMQ_DEFAULT_PASS=root rabbitmq